//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
=======
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_BD_POO_FINAL.Properties {
    using System;
    
    
    /// <summary>
<<<<<<< HEAD
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
=======
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
=======
        ///   Returns the cached ResourceManager instance used by this class.
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROYECTO_BD_POO_FINAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
=======
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_Image {
            get {
                object obj = ResourceManager.GetObject("Background Image", resourceCulture);
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background_Proceso {
            get {
                object obj = ResourceManager.GetObject("Background Proceso", resourceCulture);
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftImage {
            get {
                object obj = ResourceManager.GetObject("LeftImage", resourceCulture);
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_spinner {
            get {
                object obj = ResourceManager.GetObject("icons8-spinner", resourceCulture);
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftImage1 {
            get {
                object obj = ResourceManager.GetObject("LeftImage1", resourceCulture);
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_spinner1 {
            get {
                object obj = ResourceManager.GetObject("icons8-spinner1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SELECCIONA_UNA_OPCION {
            get {
                object obj = ResourceManager.GetObject("SELECCIONA UNA OPCION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tipo_de_proceso___Gil {
            get {
                object obj = ResourceManager.GetObject("Tipo de proceso - Gil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tipo_de_proceso___Gil1 {
            get {
                object obj = ResourceManager.GetObject("Tipo de proceso - Gil1", resourceCulture);
>>>>>>> 82dc70b6026de1a58bca889034965c12687942d9
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
